name: render readme

on:
  push:
    paths:
      - README.Rmd
  schedule:
  - cron: 0 */4 * * *

jobs:
  render:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown", "pacman", "rgeos"))'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'
      - name: Commit results
        run: |
          git add README.md man/figures/README-*
          git commit README.md -am 'Re-build README.md' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"